from antipathy import Path
from textwrap import dedent
from sys import exit
here = Path('./')
print('here: %r' % here)
if here.exists('../wholeherb_integration'):
    integration = 'wholeherb_integration'
    choice = 'whc'
    SHIP_TO_POSSIBLE = False
elif here.exists('../fis_integration'):
    integration = 'fis_integration'
    choice = 'srf'
    SHIP_TO_POSSIBLE = True
else:
    integration = ''
    choice = ''
    SHIP_TO_POSSIBLE = False

if __name__ == '__main__':
    __openerp__ = dedent("""\
    # DO NOT ADD TO git
    # AUTOMATICALLY GENERATED BY `python __init__.py`
    # (use before starting openerp if any changes)

    {
       'name': 'SalesInq Interface',
        'version': '0.4',
        'category': 'Generic Modules',
        'description': \"\""\
            Adds SalesInq tab for products and partners.
            Adds link to external, restricted, SalesInq web page.
            \"\"\",
        'author': 'Emile van Sebille',
        'maintainer': 'Emile van Sebille',
        'website': 'www.openerp.com',
        'depends': [
            "base",
            "fnx",
            "product",
            "%s",
            ],
        'css': [
            "static/src/css/salesinq.css",
            ],
        'data': [
            'res_config_view.xaml',
            '%s_res_partner_view.xaml',
            'res_users_view.xaml',
            'product_view.xaml',
            'security/salesinq_security.xaml',
            'security/ir.model.access.csv',
            'salesinq_view.xaml',
            ],
        'test': [],
        'installable': True,
        'active': False,
        }""" % (integration, choice))

    with open('__openerp__.py', 'w') as f:
        f.write(__openerp__)

    exit()

__all__ = [
        'product', 'res_partner', 'res_users', 'salesinq', 'company', 'res_config',
        'allow_custom_access', 'controllers', 'SHIP_TO_POSSIBLE']

def allow_custom_access(obj, cr, uid, context=None):
    user = obj.pool.get('res.users').browse(cr, uid, uid, context=context)
    return user.has_group('salesinq.user')

import product
import res_partner
import res_users
import salesinq
import company
import res_config
import controllers
